repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        exclude: ^package\.json
