language: node_js

os: linux
arch:
  - arm64
  - ppc64le
  - s390x

node_js:
  - '12'

notifications:
  email: false
  slack: 'hdampse:U1CJmoQ7s8a3wIZC0Wi3wWZ7'

addons:
  chrome: stable
  apt:
    packages:
      - sshpass

cache:
  directories:
    - ./app/node_modules

jobs:
  include:
    - stage: frontend-tests
      before_script:
        - cd app
        - npm install
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
        - echo "no backend / crawler / other tests specified"

    - language: python
      python: 3.7
      before_install:
        - cd etl/
        - export PYTHONPATH="${PYTHONPATH}:${pwd}"
        - python --version
      install:
        - pip install -r requirements.txt
      script:
        - python data_extraction/get_wikidata_items.py -d 1
        - python data_extraction/get_wikipedia_extracts.py

    - stage: deploy-to-staging
      if: branch = staging AND type = push
      before_script:
        - cd app
        - npm install
      script:
        - npm run build-locale
      after_success:
        - rsync -rltDvz --delete --rsh="sshpass -p ${SFTP_PASS_STAGE} ssh -o StrictHostKeyChecking=no -l ${SFTP_USER_STAGE}" ./dist/browser/* ${SFTP_USER_STAGE}@${STAGE_ADDR}:${SFTP_PATH_STAGE}

    - stage: deploy-to-production
      if: branch = master AND type = push
      before_script:
        - cd app
        - npm install
      script:
        - npm run build-locale
      after_success:
        - rsync -rltDvz --delete --rsh="sshpass -p ${SFTP_PASS_PROD} ssh -o StrictHostKeyChecking=no -l ${SFTP_USER_PROD}" ./dist/browser/* ${SFTP_USER_PROD}@${PROD_ADDR}:${SFTP_PATH_PROD}
