language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - sshpass

cache:
  directories:
    - ./node_modules

before_script:
  - cd app
  - npm install

script:
  # frontend tests
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build

  # TODO: we might want to add backend tests as well

after_success:
  # deployment (WIP)
  rsync -rltDvz --rsh="sshpass -p ${SFTP_PASS} ssh -o StrictHostKeyChecking=no -l ${SFTP_USER}" ./dist/art-browser ${SFTP_USER}@141.100.60.99:/travis-deployments/art-browser
