language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - sshpass

cache:
  directories:
    - ./node_modules

jobs:
  include:
    - stage: frontend-tests
      before_script:
        - cd app
        - npm install
      script:
        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

    - stage: backend-tests
      script:
        - echo "no backend / crawler / other tests specified"

    - stage: deploy-to-staging
      if: branch = staging # note: this also counts as base:staging in PRs
      before_script:
        - cd app
        - npm install
      script:
        - npm run build # include the staging flag
      after_success:
        - rsync -rltDvz --rsh="sshpass -p ${SFTP_PASS_STAGE} ssh -o StrictHostKeyChecking=no -l ${SFTP_USER_STAGE}" ./dist/art-browser ${SFTP_USER_STAGE}@${STAGE_ADDR}:${SFTP_PATH_STAGE}

    - stage: deploy-to-production
      if: branch = master # note: this also counts as base:master in PRs
      before_script:
        - cd app
        - npm install
      script:
        - npm run build # include the production flag
      after_success:
        - rsync -rltDvz --rsh="sshpass -p ${SFTP_PASS_PROD} ssh -o StrictHostKeyChecking=no -l ${SFTP_USER_PROD}" ./dist/art-browser ${SFTP_USER_PROD}@${PROD_ADDR}:${SFTP_PATH_PROD}
